<?php
/**
 * Created by PhpStorm.
 * User: nikitaignatenkov
 * Date: 2019-06-26
 * Time: 10:52
 */

namespace common\components\cache;


//use common\helpers\User;
use Yii;

class PageCache extends \yii\filters\PageCache
{

    const CACHE_KEY = 'reset_key_cache';

    const CACHE_DURATION = 60 * 60 * 8;

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub

//        $resetKey = Yii::$app->request->getQueryParam(self::CACHE_KEY);

//        //проверка авторизован ли user в yii админке
//        $resetKey = Yii::$app->request->getQueryParam(self::CACHE_KEY);
//        if ($resetKey && User::canResetCache()) {
//            Yii::$app->cache->delete($this->calculateCacheKey());
//        }
    }
}